[task]
name = "8_comprehensive_test"
description = "Navigate to https://parabank.parasoft.com/, login using credentials and perform banking operations with the custom instructions"
extra_instructions = [
    "Login to the website using the provided credentials",
    "Go to 'Open new account' section",
    "Create a new 'CHECKING' account and a 'SAVINGS' account",
    "Go to transfer funds section of the website",
    "Move 75$ from the first account to a different account",
    "Verify the transaction in 'Accounts Overview' and check whether the appropriate funds are available on the created accounts",
    "Log out of the platform",
]
allowed_domains = []

[secrets]
USERNAME = "test_account_username"
PASSWORD = "password_123"

[run_config]
viewport_width = 1920
viewport_height = 1080
user_agent = ""
wait_between_actions = 1.0
enable_vision = true
enable_healing = true
headless = false
enable_video_recording = true


[metadata]
task_id = "y5ripr9cy3u1mp5mfkfrxvoj"
created_date = "2025-09-14T18:52:04.121309+00:00Z"
