[task]
name = "2_simple_navigation_with_replay"
description = "Navigate to meteoblue.com, and search for New York City!\nAccess the settings, toggle temperature units twice (from Celsius → to Fahrenheit → and back to Celsius)!"
extra_instructions = []
allowed_domains = []

[run_config]
viewport_width = 1920
viewport_height = 1080
user_agent = ""
wait_between_actions = 1.0
enable_vision = true
enable_healing = true
headless = false
enable_video_recording = false

[metadata]
task_id = "uvbm4guf0yigbgs8ldbck9dx"
created_date = "2025-09-14T13:09:27.013352+00:00Z"

[metadata.summary]
total_ai_runs = 0
total_replay_runs = 0
successful_ai_runs = 0
successful_replay_runs = 0
