[task]
name = "4_self_healing"
description = "Navigate to wikipedia.com and search for Artificial Intelligence, and them open the first article."
extra_instructions = []
allowed_domains = []

[run_config]
viewport_width = 1920
viewport_height = 1080
user_agent = ""
wait_between_actions = 1.0
enable_vision = true
enable_healing = true
headless = false
enable_video_recording = true

[metadata]
task_id = "c58h39d1yo351k9p2j5g5b4d"
created_date = "2025-09-14T13:19:09.364270+00:00Z"
