[task]
name = "1_simple_navigation"
description = "Go to app.bacprep.ro/en, login to the platform via email authentication with the \nprovided credentials:\n\nemail: feligaf715@lewou.com\npassword: 9945504JA\n\nEdit the name of the user to another plausible name!\nIf successful log out and close the browser!"
extra_instructions = []
allowed_domains = []

[run_config]
viewport_width = 1920
viewport_height = 1080
user_agent = ""
wait_between_actions = 1.0
enable_vision = true
enable_healing = true
headless = false
enable_video_recording = true

[metadata]
task_id = "ln70dwbp4l8g8bxzoafsv75b"
created_date = "2025-09-14T12:44:24.995366+00:00Z"
