[task]
name = "5_secrets"
description = "Go to practicetestautomation.com/practice-test-login/ and with the provided credentials, try to log in!\nVerify the successful login, and after that log out and close the browser!"
extra_instructions = []
allowed_domains = [
    "www.practicetestautomation.com",
    "practicetestautomation.com",
]

[secrets]
EMAIL_SECRET = "student"
PASSWORD_SECRET = "Password123"

[run_config]
viewport_width = 1920
viewport_height = 1080
user_agent = ""
wait_between_actions = 1.0
enable_vision = true
enable_healing = true
headless = false
enable_video_recording = true


[metadata]
task_id = "blwju7ohsh5zyfsnwwzmtjjs"
created_date = "2025-09-14T07:21:07.205907Z"
