[task]
name = "6_extra_instructions_navigation"
description = "Navigate to Amazon homepage, search for \"wireless headphones\", browse through product listings"
extra_instructions = [
    "Open exactly three different(!) product pages after each other",
    "On the productâ€™s page read its average score",
    "Compare scores across all three products",
    "Navigate back to previously viewed products if necessary",
    "Add the product with the best single average score to the cart",
    "Close the browser afterwards",
]
allowed_domains = []

[run_config]
viewport_width = 1920
viewport_height = 1080
user_agent = ""
wait_between_actions = 1.0
enable_vision = true
enable_healing = true
headless = false
enable_video_recording = true


[metadata]
task_id = "go14qu2zci8afirdpyuwn5ks"
created_date = "2025-09-14T13:47:21.792228+00:00Z"