[task]
name = "3_mobile_viewport"
start_url = "https://ebay.com"  # REQUIRED: URL where the browser session should start
description = "Search for home surveillance.\nOrder the list from cheapest to most expensive, and scroll down until the the result page options are visible.\nNavigate to the second page of the results, and from the second page open the first product."
extra_instructions = []
allowed_domains = []  # Optional: List of allowed domains for web tasks
dependencies = []  # Optional: List of task folder names or CUIDs that this task depends on

[run_config]
viewport_width = 390
viewport_height = 844
user_agent = "Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Mobile/15E148 Safari/604.1"
wait_between_actions = 1.0
enable_vision = true
enable_healing = true
headless = false
enable_video_recording = false

[metadata]
task_id = "bcf4q4lvd21n24oypvac4i3x"
created_date = "2025-10-09T17:07:14.893094+00:00Z"
creation_type = "manually_added"
