[task]
name = "7_secrets_scrolling_replay"
description = "In this testcase we are evaluating whether we can successfully check the awards of the 10th best movie on IMDB."
extra_instructions = [
    "Navigate to https://www.imdb.com/ and login using credentials.",
    "From the menu, select the option 'Top 250' movies.",
    "Scroll, until the 10th best movie is visible, and click on it to open it's details.",
    "In the details page scroll down (or up) to lake the awards the movie have won, and click on it to check them out!",
    "After that is done, log out of the platform and close the browser.",
]
allowed_domains = []

[secrets]
EMAIL_CREDENTIAL = "cofahif360@ekuali.com"
PASSWORD_CREDENTIAL = "test_bugninja_2025"

[run_config]
viewport_width = 1920
viewport_height = 1080
user_agent = "Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Mobile/15E148 Safari/604.1"
wait_between_actions = 1.0
enable_vision = true
enable_healing = true
headless = false
enable_video_recording = true


[metadata]
task_id = "h4dc0f9q2xuy2w2l6i8y70x3"
created_date = "2025-09-14T13:54:31.002461+00:00Z"
