[task]
name = "7_secrets_scrolling_replay"
start_url = "https://www.imdb.com/"  # REQUIRED: URL where the browser session should start
description = "In this testcase we are evaluating whether we can successfully check the awards of the 10th best movie on IMDB."
extra_instructions = [
    "Login using credentials.",
    "From the menu, select the option 'Top 250' movies.",
    "Scroll, until the 10th best movie is visible, and click on it to open it's details.",
    "In the details page scroll down (or up) to lake the awards the movie have won, and click on it to check them out!",
    "After that is done, log out of the platform and close the browser.",
]
allowed_domains = []
dependencies = []  # Optional: List of task folder names or CUIDs that this task depends on

[secrets]
EMAIL_CREDENTIAL = "cofahif360@ekuali.com"
PASSWORD_CREDENTIAL = "test_bugninja_2025"

[run_config]
# CLI-specific runtime configuration
viewport_width = 1920
viewport_height = 1080
user_agent = "Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Mobile/15E148 Safari/604.1"
wait_between_actions = 1.0
enable_vision = true
enable_healing = true
headless = false
enable_video_recording = true

[metadata]
task_id = "c74hyd4ji37cw7lab0z7qr72"
created_date = "2025-10-09T17:21:40.032140+00:00Z"
creation_type = "manually_added"
