[task]
name = "92_ebay_book_search"
start_url = "https://www.ebay.com/"  # REQUIRED: URL where the browser session should start
description = "We will search for a book called 'Of Mice and Men' on Ebay"
extra_instructions = [
    "Search for the book 'Of Mice and Men'",
    "Extract the FIRST price of the book from the search results."
]
allowed_domains = ["ebay.com", "www.ebay.com"]
dependencies = ["91_amazon_book_search"]


[task.io_schema]
input_schema.BOOK_PRICE = "First price of the book on Amazon"
output_schema.BOOK_AMAZON_PRICE = "First price of the book on Amazon"
output_schema.BOOK_EBAY_PRICE = "First price of the book on Ebay"

[run_config]
# CLI-specific runtime configuration
viewport_width = 1920
viewport_height = 1080
user_agent = ""
wait_between_actions = 1.0
enable_vision = true
enable_healing = true
headless = false
enable_video_recording = true

[metadata]
task_id = "kpo0wmdhi73qe9obs6k95qvw"
created_date = "2025-10-09T09:20:22.403896+00:00Z"
creation_type = "manually_added"
